### PR TITLE
Migrate to GitHub Actions from CircleCI

### PR DESCRIPTION
**Pull request by koic**
This PR will centralize CI to GitHub Actions as introduced in https://github.com/rubocop/rubocop-performance/pull/388.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-performance/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by Earlopain** [comment]
Hey @koic, locally I'm getting the failures you excluded for JRuby with CRuby, but only when running the full spec suite with `bundle exec rspec` or `bunde exec rake` (seed is `26805` if thats important). If I run the file in isolation with `bundle exec rspec spec/rubocop/cop/performance/sum_spec.rb` tests pass. Do you encounter the same thing?

I wonder if this is something I should be looking into, but if its only me I wouldn't bother. I regenerated my lockfile but I can't say if that is related to that.

**Comment by koic** [comment]
Hm, I couldn't reproduce it on my local environment. It also passes when using the seed.

**Comment by Earlopain** [comment]
I think I figured it out. Not sure why it's not failing for you though. Will open a PR.

**Comment by Earlopain** [comment]
Well, not really. I bisected it down to the following order `bundle exec rspec ./spec/rubocop/cli/autocorrect_spec.rb:16 ./spec/rubocop/cop/performance/sum_spec.rb:5` and the culprid seemed to be overriding the default config here without resetting it: https://github.com/rubocop/rubocop-performance/blob/47c0de54cfdbee96af16dddcdf556c8aaf355cfb/spec/rubocop/cli/autocorrect_spec.rb#L11-L13 (how incredibly cool is `rspec --bisect`, TIL)

Solution seemed simple enough by changing it into this:
```rb
  around do |ex|
    previous_config = RuboCop::ConfigLoader.default_configuration

    RuboCop::ConfigLoader.default_configuration = nil
    RuboCop::ConfigLoader.default_configuration.for_all_cops['SuggestExtensions'] = false
    RuboCop::ConfigLoader.default_configuration.for_all_cops['NewCops'] = 'disable'
    ex.call
  ensure
    RuboCop::ConfigLoader.default_configuration = previous_config
  end
```

which did remove the failures. But now I'm not getting failures anymore at all even with the command that previously reliably produced them without changes to the code, and other specs in rubocop also do the same pattern without problems. So I'm a bit stumped again :shrug:

**Pull request merged**
